FROM openjdk:9.0.1-jdk-slim

LABEL maintainer="kodability"
LABEL name="kodability test with jdk9"

RUN apt-get update && apt-get install -y make

RUN mkdir /test

COPY . /test

WORKDIR /test
CMD make all
