FROM openjdk:8-jdk-alpine

LABEL maintainer="kodability"
LABEL name="kodability test using jdk8"

RUN apk add --update make wget

RUN mkdir /test

COPY . /test

WORKDIR /test
RUN make dep

CMD make all
