FROM openjdk:10-jdk-slim

LABEL maintainer="kodability"
LABEL name="kodability test using jdk10"

RUN apt-get update && apt-get install -y make wget

RUN mkdir /test

COPY . /test

WORKDIR /test
RUN make dep

CMD make all
