FROM python:3.6-alpine

LABEL maintainer="kodability"
LABEL name="kodability test using python 3.6"

RUN apk add --update make

RUN mkdir /test

COPY . /test

WORKDIR /test
RUN pip3 install unittest-xml-reporting

CMD make test
