FROM frolvlad/alpine-scala:2.12

LABEL maintainer="kodability"
LABEL name="kodability test with scala 2.12"

RUN apk add --update make wget

RUN mkdir /test

COPY . /test

WORKDIR /test
RUN make dep

CMD make all
