FROM groovy:2.4-jre8-alpine

LABEL maintainer="kodability"
LABEL name="kodability test using groovy 2.4"

USER root
RUN apk add --update make

RUN mkdir /test

COPY . /test

WORKDIR /test
CMD make all
