FROM groovy:3.0-jre8-alpine

LABEL maintainer="kodability"
LABEL name="kodability test with groovy 2.4"

USER root
RUN apk add --update make

RUN mkdir /test

COPY . /test

WORKDIR /test
CMD make all
